spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: crypto-bot
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.springframework: INFO

app:
  services-url: "analyzer-service=http://analyzer-service:8080/actuator/health,event-listener-service=http://event-listener:8080/actuator/health,event-listener-topics-updates=http://event-listener:8080/topics-update-time,trade-manager-service=http://trade-manager-service:8080/actuator/health"
