spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: crypto-bot
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  mvc:
    dispatch-options-request: true

logging:
  level:
    org.springframework: INFO

app:
  services-url: "analyzer-service=http://localhost:8701/actuator/health,event-listener-service=http://localhost:8702/actuator/health,event-listener-topics-updates=http://localhost:8702/topics-update-time,trade-manager-service=http://localhost:8703/actuator/health"
  joat-token-address: "0x2154481753c3717Cb66b836fC6e9087C89c6Ff73"
  blockchain-address: "https://sepolia.infura.io/v3/833bc9ae0e7a4d899cb8a78de45081ed"
