spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: crypto-bot
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  mvc:
    dispatch-options-request: true

logging:
  level:
    org.springframework: DEBUG

app:
  services-url: "analyzer-service=http://localhost:8701/actuator/health,event-listener-service=http://localhost:8702/actuator/health,event-listener-topics-updates=http://localhost:8702/topics-update-time,trade-manager-service=http://localhost:8703/actuator/health"
