spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  data:
    mongodb:
      host: localhost
      port: 27017
      database: crypto-bot
    redis:
      host: localhost
      port: 6379

server:
  port: 8701
