version: "3"

services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ message broker port
      - "15672:15672" # RabbitMQ management console port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - "crypto-bot-network"

  mongodb:
    image: mongo:latest
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"
    command: "mongod --replSet rs0"
    volumes:
      - "mongodb_data:/data/db"
    healthcheck:
      test: mongosh --eval 'try { rs.initiate(); } catch(e) {} rs.status().ok;' || exit 1
      retries: 1
    networks:
      - "crypto-bot-network"

  redis:
    image: redis:latest
    hostname: redis
    restart: always
    networks:
      - "crypto-bot-network"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  event-listener:
    build:
      context: .
      dockerfile: dockerfiles/EventListenerDockerfile
    environment:
      spring.profiles.active: docker-local
      SPRING_AMQP_DESERIALIZATION_TRUST_ALL: true
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - "crypto-bot-network"

  analyzer-service:
    build:
      context: .
      dockerfile: dockerfiles/AnalyzerServiceDockerfile
    environment:
      spring.profiles.active: docker-local
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      event-listener:
        condition: service_started
    networks:
      - "crypto-bot-network"

  api-service:
    build:
      context: .
      dockerfile: dockerfiles/ApiServiceDockerfile
    environment:
      spring.profiles.active: docker-local
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - "crypto-bot-network"

  trade-manager-service:
    build:
      context: .
      dockerfile: dockerfiles/TradeManagerDockerfile
    environment:
      spring.profiles.active: docker-local
      SPRING_AMQP_DESERIALIZATION_TRUST_ALL: true
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - "crypto-bot-network"

  ui:
    build:
      context: crypto-bot-ui
      dockerfile: ../dockerfiles/UIDockerfileLocal
    depends_on:
      - api-service
    ports:
      - "3000:80"
    networks:
      - "crypto-bot-network"
    volumes:
      - "./init-files/nginx.conf:/etc/nginx/conf.d/default.conf"

volumes:
  zookeeper_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  crypto-bot-network:
