version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ message broker port
      - "15672:15672" # RabbitMQ management console port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  mongodb:
    image: mongo:latest
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"
    command: "mongod --replSet rs0"
    volumes:
      - "mongodb_data:/data/db"
    healthcheck:
      test: mongosh --eval 'try { rs.initiate(); } catch(e) {} rs.status().ok;' || exit 1
      retries: 1

volumes:
  mongodb_data:
    driver: local

