spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: crypto-bot
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

server:
  port: 8702
