package space.dawdawich.constants

const val BYBIT_TICKER_TOPIC = "bybit_ticker"
const val BYBIT_TEST_TICKER_TOPIC = "bybit_ticker"
const val SYMBOL_REINITIALIZE_TOPIC = "symbol_reinitialize"
const val DEACTIVATE_ANALYZER_TOPIC = "deactivate_analyzer"
const val ACTIVATE_ANALYZER_TOPIC = "activate_analyzer"
const val DELETE_ANALYZER_TOPIC = "delete_analyzer"
const val REQUEST_PROFITABLE_ANALYZER_STRATEGY_CONFIG_TOPIC = "request_profitable_analyzer_strategy_config"
const val RESPONSE_PROFITABLE_ANALYZER_STRATEGY_CONFIG_TOPIC = "response_profitable_analyzer_strategy_config"
const val REQUEST_ANALYZER_STRATEGY_RUNTIME_DATA_TOPIC = "request_analyzer_strategy_runtime_data"
const val RESPONSE_ANALYZER_STRATEGY_RUNTIME_DATA_TOPIC = "response_analyzer_strategy_runtime_data"
const val REQUEST_MANAGER_TOPIC = "request_manager"
const val RESPONSE_MANAGER_TOPIC = "response_manager"
const val ACTIVATE_MANAGER_TOPIC = "activate_manager"
const val DEACTIVATE_MANAGER_TOPIC = "deactivate_manager"
