spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: crypto-bot

logging:
  level:
    space.dawdawich.strategy.strategies: DEBUG
