spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  data:
    mongodb:
      host: localhost
      port: 27017
      database: crypto-bot

logging:
  level:
    org.springframework: INFO

server:
  port: 8703
