package space.dawdawich.configuration.model

import org.springframework.security.core.GrantedAuthority
import org.springframework.security.core.userdetails.User

/**
 * Class representing the details of a wallet account.
 *
 * @param address The address of the wallet account.
 * @param signature The signature associated with the wallet account. Generated by our server.
 * @param authorities The list of authorities assigned to the wallet user.
 * @param salt The salt value associated with the wallet account. Generated by our server, represents an expiration time.
 */
class WalletUserDetails(address: String, signature: String, authorities: List<GrantedAuthority>, val salt: Long) :
    User(address, signature, authorities) {
    val address: String get() = username
    val signature: String get() = password
}
