package space.dawdawich.configuration.model

import org.springframework.security.authentication.UsernamePasswordAuthenticationToken

/**
 * Class representing a wallet authentication request.
 *
 * @property address The wallet's account address.
 * @property signature The signature associated with the wallet address. Generated by our server.
 */
class WalletAuthenticationRequest(address: String, signature: String) : UsernamePasswordAuthenticationToken(address, signature) {
    init {
        isAuthenticated = false
    }

    val address: String get() = principal.toString()
    val signature: String get() = credentials.toString()
}
